name: Node.js CI/CD

on: [push]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: my-app  # Nome do seu aplicativo no Azure
  AZURE_WEBAPP_PACKAGE_PATH: 'my-app-path'  # Caminho para o seu projeto
  NODE_VERSION: '18.x'  # Versão do Node.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@v3
   
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'Install, Build, and Test'
      run: |
        npm install
        npm run build --if-present
        npm test --if-present
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
               
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Logout from Azure'
      run: |
        az logout